apiVersion:  apps/v1
kind: ReplicaSet
metadata:
  name: replicas-with-services
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      service: replicas-with-services
  template:
    metadata:
      labels:
        type: backend
        service: replicas-with-services
        db: mongo
        language: go
    spec:
      containers:
      - name: db
        image: mongo:3.3
        command: ["mongod"]
        args: ["--rest", "--httpinterface"]
        ports:
        - containerPort: 28017
          protocol: TCP
          
      - name: api
        image: vfarcic/go-demo-2
        env:
        - name: DB
          value: localhost
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080