apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-db
spec:
  selector:
    matchLabels:
      type: db
      service: replicaset-db

  template:
    metadata:
      labels:
        type: db
        service: replicaset-db

    spec:
      containers:
        - name: db
          image: mongo:3.3
          ports:
            - containerPort: 28017

---
apiVersion: v1
kind: Service
metadata:
  name: replicaset-db
spec:
  selector:
    type: db
    service: replicaset-db
  ports:
    - port: 27017

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app
      service: replicaset-app
  template:
    metadata:
      labels:
        type: app
        service: replicaset-app
    spec:
      containers:
        - name: api
          image: btholt/node-app
          env:
            - name: MONGO_CONNECTION_STRING
              value: mongodb://db:27017
          readinessProbe:
            httpGet:
              path: /demo/hello
              port: 8080
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /demo/hello
              port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: replicaset-app
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    type: app
    service: replicaset-app
